// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class QuizTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void quiz() {
    driver.get("http://quiz-fe-test.hematitecorp.com/");
    driver.manage().window().setSize(new Dimension(736, 860));
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("admin@gmail.com");
    driver.findElement(By.id("password")).sendKeys("Admin@1234");
    driver.findElement(By.cssSelector(".MuiButton-contained")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(2) .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(3) > .MuiButtonBase-root")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(4) .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(5) > .MuiButtonBase-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-outlined")).click();
    driver.findElement(By.cssSelector(".css-2nc5gr")).click();
    driver.close();
  }
}
